apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: testingress
  namespace: certsync
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
    - nginxtesttom.com
    secretName: nginx-cert
  rules:
  - host: nginxtesttom.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: test
            port:
              number: 80